<?php
if (!defined("PJ_HOST")) define("PJ_HOST", "localhost");
if (!defined("PJ_USER")) define("PJ_USER", "senio243_s1mpl3cms2020");
if (!defined("PJ_PASS")) define("PJ_PASS", "s1mpl32020cms");
if (!defined("PJ_DB")) define("PJ_DB", "senio243_s1mpl3-cms2020");
if (!defined("PJ_PREFIX")) define("PJ_PREFIX", "");
if (!defined("PJ_INSTALL_FOLDER")) define("PJ_INSTALL_FOLDER", "/simplecms/");
if (!defined("PJ_INSTALL_PATH")) define("PJ_INSTALL_PATH", "/home/senio243/public_html/simplecms/");
if (!defined("PJ_INSTALL_URL")) define("PJ_INSTALL_URL", "https://www.seniorsunitednow.com/simplecms/");
if (!defined("PJ_SALT")) define("PJ_SALT", "JSJ85YPO");
if (!defined("PJ_INSTALLATION")) define("PJ_INSTALLATION", "MTIyMjI1MjEwMjQ2NDM0NzgxMDU1MDg4NjgzNTgxNTA4NzM0MzQ1ODYzNDg0OTgyMDMwNTk0MDgxMzkwNTAxODk3NzYwMjUxNjIxNTQxMTM5MTk0ODU5MjczMTM3NTM2ODcwMSA1MzczNzgzODc2OTYxMTIyMzUzNjExODc1ODQwODk2NDA2NjE4NTcwMDU1OTY0NTA0NzI5ODkwMjczMDcxODM2NzU5MzY2NDg4MzE5Mjg4NzUxMDgzNDY3MDA0NDgyNDEyMTAgMTM0NjYyODQ3OTA1NzMzOTA4NDY0MzM3NjUwMTUwOTIyMDU4NDY4NjcwMTM0OTY5MDA2MzAxNTU1NTgxNjEyMzYxOTczMjY2ODI2MDM2MDM0MTY4MjUzNjgyMTI5MTk1OTQxMCAxMzU1NzkzNTc1MDQ0NzIyNDIxMzM2NzExNDU2MTczOTg4MjA4ODQxMTc4MDc4MDEzMTc2ODIzMDA3NzE2MjI1OTA2MTAwMDg0ODU0MzcxMjQ3NjMyOTY3NjU4ODU5MjU0NDMzIDg3NTU4Mzg2MjQ3MTY0ODk1MjcxNzQ0MTczMTU4NTU2NzQzMjUxODU5MjI2OTA5ODUxMTYzODI2NzA2MTAyMTE4MzQwMDMzNTcxOTg1NTcwMzc4MDgyMjM5ODI1MzMzNTgwOCAzMzM4MTQ1NjU1MTIwMDM5Mjk0MjQ4Njg3MjIxNTcxMjA5NTU3MzE5MzcwMDY1NjY1MTIzNjIyNjYzMzY5MjIwMzQzMDYzMzgyODQ2MDc1Njg1NTcwODI0OTY5MDIzMTEwNDggNDEzNjE3NzE5Mjk3MTUzNjQ4MTMyMzMxNzgwMDA0ODYzNjM5MDI3MDUyNjM4MzAyNDAzNTQzMDg1OTg1MDI1NjEyODEzNzE0MDQ2NzMzNjQzNTgyNjUwNDYxODU5MzY4NTk5IDE2MzUyMzczODkwMTc5MTU2MzkxNzE4MDY1ODQ1NDUyNTA5MjY4NTU2NDk3MjIyODQ5Nzk5NDMyNDgxODAzODQyODY2NjI5NDk4OTQwNjczNDI3NzIzNTYwMzE4Njg0MTEzMA==");
?>